server:
  port: 8081

spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "password"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true